name: json_serializable
version: 3.5.1
description: >-
  Automatically generate code for converting to and from JSON by annotating
  Dart classes.
repository: https://github.com/google/json_serializable.dart
environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  analyzer: any
  build: any
  build_config: any

  # Use a tight version constraint to ensure that a constraint on
  # `json_annotation` properly constrains all features it provides.
  # For v3 only – allow a wide range since the only change was to REMOVE things
  # from json_annotation
  json_annotation: '>=3.1.0 <3.2.0'
  meta: ^1.3.0
  path: ^1.8.0
  source_gen: ^0.9.6

dev_dependencies:
  build_runner: any
  build_verify: any
  collection: ^1.14.0
  dart_style: ^1.2.0
  logging: ^1.0.1
  pub_semver: ^2.0.0
  source_gen_test: ^0.1.0
  test: any
  yaml: '>=2.0.0 <=3.0.0'
